export const config = {
    RPC_URL: 'https://chtd-rpc.skynetvalidators.com',
    REST_URL: 'https://chtd-rpc.skynetvalidators.com',
    EXPLORER_URL: 'https://chronic.zenscan.io',
    STAKING_URL: 'https://chronicdex.netlify.app/stake',
    NETWORK_NAME: 'Chronic-Chain',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'morocco-1',
    CHAIN_NAME: 'Chronic Token',
    COIN_DENOM: 'CHT',
    COIN_MINIMAL_DENOM: 'ucht',
    COIN_DECIMALS: 6,
    PREFIX: 'chronic',
    COIN_TYPE: 118,
    COINGECKO_ID: '',
    GAS_PRICE_STEP_LOW: 25,
    GAS_PRICE_STEP_AVERAGE: 30,
    GAS_PRICE_STEP_HIGH: 50,
    FEE_CURRENCY: 'CGAS',
    FEATURES: ['ibc-transfer', 'ibc-go'],
};
